"""
catalog_agent.py — Queries NotebookLM with Vawn's catalog to find quotable bars
matching today's trend angles.
"""

import asyncio
import json
import sys
sys.path.insert(0, r"C:\Users\rdyal\Vawn")
from vawn_config import (
    load_json, save_json, DAILY_BRIEF, NOTEBOOKLM_STATE,
    CATALOG_HTML, log_run, today_str,
)


async def ensure_notebook():
    """Create or load the Vawn Catalog notebook in NotebookLM."""
    from notebooklm import NotebookLMClient

    state = load_json(NOTEBOOKLM_STATE)

    async with await NotebookLMClient.from_storage() as client:
        if "notebook_id" in state:
            try:
                nb = await client.notebooks.get(state["notebook_id"])
                print(f"[CatalogAgent] Using existing notebook: {nb.title} ({nb.id})")
                return state["notebook_id"]
            except Exception:
                print("[CatalogAgent] Stored notebook not found, creating new one")

        nb = await client.notebooks.create("Vawn Catalog")
        print(f"[CatalogAgent] Created notebook: {nb.id}")

        catalog_text = CATALOG_HTML.read_text(encoding="utf-8")
        source = await client.sources.add_text(
            nb.id,
            title="Vawn Full Lyrics Catalog",
            content=catalog_text,
            wait=True,
            wait_timeout=120.0,
        )
        print(f"[CatalogAgent] Added catalog source, waiting for processing...")

        state["notebook_id"] = nb.id
        save_json(NOTEBOOKLM_STATE, state)
        return nb.id


async def query_catalog(notebook_id, trend_angles):
    """Query NotebookLM for quotable bars matching today's trends."""
    from notebooklm import NotebookLMClient

    angles_str = "\n".join([f"- {a}" for a in trend_angles])

    query = f"""Given these social media content themes for today:
{angles_str}

Find 3 of the most quotable, scroll-stopping lines from Vawn's catalog.

For each line, give me:
1. The exact bar (word for word)
2. Which track
3. Territory (Fear of Failure, Dependability, Love, Journey)
4. A ready-to-post Instagram hook (under 15 words) that uses this bar
5. A ready-to-post X/Twitter post (under 200 chars) built around this bar
6. A TikTok POV line (starts with "POV:" + 3-5 words)

Pick bars that HIT on their own — no context needed to understand them."""

    async with await NotebookLMClient.from_storage() as client:
        result = await client.chat.ask(notebook_id, query)
        return result


def parse_catalog_response(response_text):
    """Parse NotebookLM response into structured catalog lines."""
    from vawn_config import get_anthropic_client
    client = get_anthropic_client()

    resp = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=1200,
        messages=[{"role": "user", "content": f"""Parse this NotebookLM response about Vawn lyrics into JSON.

RESPONSE:
{response_text}

Return EXACTLY this JSON structure — no markdown fencing, raw JSON only:
{{
  "catalog_lines": [
    {{
      "bar": "exact quoted lyric line",
      "track": "TRACK NAME IN CAPS",
      "territory": "Fear of Failure|Dependability|Love|Journey",
      "ig_hook": "ready-to-post Instagram hook under 15 words",
      "x_post": "ready-to-post X/Twitter caption under 200 chars with 1-2 hashtags",
      "tiktok_pov": "POV: 3-5 words"
    }}
  ]
}}

Return 3 lines. Use only bars actually quoted. Generate the ig_hook, x_post, and tiktok_pov yourself if the response doesn't include them."""}],
    )

    text = resp.content[0].text
    try:
        if "```" in text:
            text = text.split("```")[1]
            if text.startswith("json"):
                text = text[4:]
            text = text.strip()
        return json.loads(text)
    except json.JSONDecodeError:
        return {"catalog_lines": []}


def try_local_catalog(angles):
    """Try to get bars from local catalog first (no API needed)."""
    try:
        sys.path.insert(0, r"C:\Users\rdyal\Apulu Universe\pipeline")
        from brain.catalog_local import pick_bars_for_themes
        bars = pick_bars_for_themes(angles, count=3)
        if bars and len(bars) >= 2:
            # Format as catalog_lines
            return [
                {
                    "bar": b["bar"].split("\n")[0],  # first line as the quotable
                    "track": b["track"],
                    "territory": b["territory"],
                    "ig_hook": "",  # will be generated by Claude below
                    "x_post": "",
                    "tiktok_pov": "",
                    "_source": "local_catalog",
                }
                for b in bars
            ]
    except Exception as e:
        print(f"[CatalogAgent] Local catalog failed: {e}")
    return None


def enrich_bars_with_hooks(catalog_lines):
    """Use Claude to generate ig_hook, x_post, tiktok_pov for local catalog bars."""
    from vawn_config import get_anthropic_client
    client = get_anthropic_client()

    bars_text = "\n".join([f"- \"{l['bar']}\" (from {l['track']}, {l['territory']})" for l in catalog_lines])

    resp = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=800,
        messages=[{"role": "user", "content": f"""For each bar below, generate:
1. ig_hook: Instagram hook under 15 words
2. x_post: X/Twitter post under 200 chars with 1-2 hashtags
3. tiktok_pov: starts with "POV:" + 3-5 words

Bars:
{bars_text}

Return ONLY JSON array:
[{{"bar": "...", "ig_hook": "...", "x_post": "...", "tiktok_pov": "..."}}]"""}],
    )

    try:
        text = resp.content[0].text
        start = text.find("[")
        end = text.rfind("]") + 1
        hooks = json.loads(text[start:end])
        for i, hook in enumerate(hooks):
            if i < len(catalog_lines):
                catalog_lines[i]["ig_hook"] = hook.get("ig_hook", "")
                catalog_lines[i]["x_post"] = hook.get("x_post", "")
                catalog_lines[i]["tiktok_pov"] = hook.get("tiktok_pov", "")
    except Exception as e:
        print(f"[CatalogAgent] Hook enrichment failed: {e}")

    return catalog_lines


def run():
    brief = load_json(DAILY_BRIEF)

    trends = brief.get("trends", [])
    angles = [t.get("angle", "") for t in trends[:3]]
    if not angles:
        angles = ["authenticity and real talk", "behind the scenes process", "quotable bars"]

    # Try local catalog first (no API dependency)
    local_bars = try_local_catalog(angles)
    if local_bars:
        print(f"[CatalogAgent] Local catalog hit — {len(local_bars)} bars matched")
        local_bars = enrich_bars_with_hooks(local_bars)
        brief["catalog_lines"] = local_bars
        save_json(DAILY_BRIEF, brief)
        log_run("CatalogAgent", "ok/local", f"{len(local_bars)} bars from local catalog")
        print(f"[CatalogAgent] {len(local_bars)} catalog lines written (local)")
        return {"catalog_lines": local_bars}

    # Fall back to NotebookLM
    print("[CatalogAgent] Local catalog miss — trying NotebookLM")
    try:
        notebook_id = asyncio.run(ensure_notebook())
        raw_response = asyncio.run(query_catalog(notebook_id, angles))

        response_text = str(raw_response)
        parsed = parse_catalog_response(response_text)

        brief["catalog_lines"] = parsed.get("catalog_lines", [])
        save_json(DAILY_BRIEF, brief)

        log_run("CatalogAgent", "ok", f"{len(parsed.get('catalog_lines', []))} lines found")
        print(f"[CatalogAgent] {len(parsed.get('catalog_lines', []))} catalog lines written")
        return parsed

    except Exception as e:
        log_run("CatalogAgent", "error/fallback", str(e))
        print(f"[CatalogAgent] ERROR: {e}")
        print(f"[CatalogAgent] Using verified fallback bars (actual lyrics)")
        # These are VERIFIED exact bars from the catalog — do not edit without checking the HTML
        brief["catalog_lines"] = [
            {
                "bar": "I don't carry anger — I carry receipts",
                "track": "GOT THAT IN WRITING",
                "territory": "Fear of Failure",
                "ig_hook": "Receipts, not anger. The work speaks.",
                "x_post": "I don't carry anger — I carry receipts. #hiphop #bars",
                "tiktok_pov": "POV: they doubted you in writing",
                "_fallback": True,
            },
            {
                "bar": "This the version that survived it all",
                "track": "THE VERSION THAT SURVIVED",
                "territory": "Journey",
                "ig_hook": "Not the version I planned. The one that walked out.",
                "x_post": "This the version that survived it all. Not the one I planned. #hiphop",
                "tiktok_pov": "POV: you survived your own plan",
                "_fallback": True,
            },
            {
                "bar": "I chose this and I choose it every morning when I wake up",
                "track": "I CHOSE THIS",
                "territory": "Fear of Failure",
                "ig_hook": "Every morning. Same choice. No one asked me to.",
                "x_post": "I chose this and I choose it every morning when I wake up. #newmusic",
                "tiktok_pov": "POV: 5am and you chose this again",
                "_fallback": True,
            },
        ]
        save_json(DAILY_BRIEF, brief)
        return {"catalog_lines": brief["catalog_lines"]}


if __name__ == "__main__":
    run()
